### ISSUE TITLE
mvn install fails with de_AT locale

### ISSUE THREAD

**Issue by janrn** [keeps/roda-in#104]
I tried to build roda-in from source, but my version of Ubuntu (14.04) is running with de_AT language setting. This caused an error with the properties, because there is no "lang_de.properties" file and apparently no default setting either (or it's not working), if the detected language is neither English nor Portuguese.

This was not reflected in the log files in /surefire-reports, instead there have been random and different errors after every (failed) build process.

I managed to "fix" this by creating a copy of the English properties file and renaming it to lang_de.properties.

**Comment by adrapereira** [comment]
There are some error messages when there's no language file for the default locale, but the application should start anyway using the English language. There were some problems with the language in the tests, I think that's why it failed. 

Can you pull the new version of the code and check if it works?

**Comment by janrn** [comment]
Yes, it works with the updated version.
