### ISSUE TITLE
Metadata association is not working

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#239]
Tested:

- Load from single file
- Load from one directory

Both, not working.

**Comment by hsilva-keep** [comment]
@jmaferreira actually this is not working because you are not selecting the correct metadata type. 
I.e., and using the corpora that you've provided, if you select a metadata file (which is simpledc) and say it is ead2002, what RODA-in is doing is using the template for ead2002 ("as you told RODA-in to do") and in the background using the simpledc provided (which is wrong, and this is actually the information put inside the SIP produced). The same goes for the option where metadata file from a folder are match with data files with the same name.

Let me remember you that these comboboxes were added to the metadata pane so RODA-in knows what metadata type those files are & put that metadata in the SIP produced.

**To solve this**, we should answer the following question: if we choose a metadata file (single or via match option) and choose a specific metadata type (combobox; different from the chosen file/files), which one should take precedence?

In my opinion, precedence should be given to the chosen metadata type and, in that case, we should validate each of the metadata files against the schema (if any) associated to that metadata type.

**Comment by jmaferreira** [comment]
You have to show me for me to believe it. I’ve demonstrated today that even choosing the right metadata type it wont work. Sebastien has experimented that for over 2 days when dealing with the problem.

Maybe your refactor magically fixed it?!

**Comment by hsilva-keep** [comment]
@jmaferreira Indeed the behavior you've described is happening in beta3 (latest jar release) & the bahavior I've described happens in the code available in the master branch (with my refactors but also with one commit from Sebastien).
Nevertheless, when facing the problem I've described before (chosing a metadata file from one type & stating in the combobox that it is from another), what should be the procedure?

**Comment by jmaferreira** [comment]
Let’s talk tomorrow… Its 23h45 and I had 3 glasses of whiskey... I’m afraid to make the wrong decision.

**Comment by hsilva-keep** [comment]
Ok. After the talk me & @jmaferreira had, it has been decided that, using the metadata association options mentioned before, if a user provides one or more files from a metadata type X and say (in the combobox) that the metadata type is Z, the app will try to validate the provided file against the type Z and, as it will fail, we will only show the raw xml (not showing the metadata form).

**Comment by hsilva-keep** [comment]
@jmaferreira I've released a new version [(2.0.0-beta4)](https://github.com/keeps/roda-in/releases/tag/2.0.0-beta4) which solves this issue. Can you please test it?

**Comment by hsilva-keep** [comment]
After talking with @jmaferreira , this issue can be solved as it is solved & tested.
