### ISSUE TITLE
Add a label called "Documentation" to left side of the "book" button. 

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#246]
Users claim that the functionality is not easy to find.

![screen shot 2017-03-21 at 15 46 40](https://cloud.githubusercontent.com/assets/3181302/24150204/c4a34fcc-0e4d-11e7-8cf8-35f490b57941.png)

**Comment by hsilva-keep** [comment]
In that case, for coherence reasons, the same must be done when seeing the documentation and displaying the button to change back to the data view.

**Comment by jmaferreira** [comment]
That is correct.

**Comment by chalkos** [comment]
![image](https://cloud.githubusercontent.com/assets/98429/24206100/33fb7666-0f15-11e7-9eab-f06ebb432ed6.png)

![image](https://cloud.githubusercontent.com/assets/98429/24206028/f955b45e-0f14-11e7-88f4-ed9b03d0314c.png)

![image](https://cloud.githubusercontent.com/assets/98429/24206091/2a4dcb32-0f15-11e7-8080-3c062387768e.png)

I added the text to the left, as instructed, styled like other text in the same panel.

But it seems a bit out of place and confusing considering that the text to the left is always the opposite, but both are styled in the same way.

I tried it as text inside the button, white, bold and capitalised instead of uppercased:

![image](https://cloud.githubusercontent.com/assets/98429/24207055/de709dd6-0f17-11e7-8b0b-13e584cc0d39.png)

![rsz_screenshot_from_2017-03-22_15-56-39](https://cloud.githubusercontent.com/assets/98429/24207246/56c95e9e-0f18-11e7-9a90-15a5a0092fa7.png)

**Comment by jmaferreira** [comment]
I like the last two screenshots (normal, hover).
Suggestion: reduce the horizontal spacing between the icon and its text on the left. Maintain the button hover effect.
