### ISSUE TITLE
New documentation descriptive metadata should not change main information

### ISSUE THREAD

**Issue by nunovieira220** [keeps/roda-in#258]
For example, when changing the title content.. it is updating the title content of the other descriptive metadata and the name of the folder on the information package section

**Comment by chalkos** [comment]
The problem was just the `title` field, that was being synchronised between all metadata types (and also synchronised with the SIP name and the header text).

This was fixed by adding a possibility (through configuration) to ignore synchronising the title of specific metadata types. To avoid synchronizing the title for a metadata type, use the following configuration

```
metadata.<name>.synchronized=false
```
