### ISSUE TITLE
Assess the EAD template attached and see why it can't be loaded into RODA-in

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda-in#278]
It would be nice if we could choose between several EAD2002 templates on GUI. We would like Record Creators to use Roda-in, changing the EAD2002.xml in the file system is not really the most user-friendly way.

We have made the EAD template for SIP 4, added more tags, but ending with an error message at validation. eadid and eadtitle elements are mandatory, they should take the value of unitid and unittitle

**Include the attached template in the Hungarian RODA-in distribution** 

[ead2002.xml.hbs.zip](https://github.com/keeps/roda-in/files/989552/ead2002.xml.hbs.zip)

**Comment by chalkos** [comment]
I used the provided template and it passed the validation. I even filled out the new elements (unitdate and abstract) and the XML file still passed validation. Could you check if this is the same template file that you were having trouble with?

I understand that the `eadid` element should have the same contents as the element `unitid`, but I have not yet tested if this is possible according to the xml schema.
But I could not find any references to eadtitle in the attached template nor the ead2002 xml schema file.

About attaching this template to the hungarian RODA-in distribution, is this template supposed to replace the ead2002 template or should both be available?

**Comment by jmaferreira** [comment]
I'm not sure of any of these questions. Do you mind asking Zoltan about it?

**Comment by chalkos** [comment]
I sent an email with these questions. This issue is on hold until we have information on how to proceed.

**Comment by hsilva-keep** [comment]
This issue is related to #290.

**Comment by hsilva-keep** [comment]
To sum up this issue:
1. The main problem was related to validating metadata & this functionality malfunctioning in windows (solved; issue #290)
2. Having several templates for EAD and selecting them in the interface. RODA-in works the following way: it has one or more "metadata formats", which one having a name, a type & a version (e.g. for putting in METS file if the SIP format uses METS), a template (for building the edit form) and a xml schema (for metadata validation). And, in the interface, when choosing which metadata format you will use, you are commiting with all those decisions. So, the only way RODA-in allows one to have several templates for EAD 2002 is to have several "metadata formats": different names, different templates, most probably same type & version & xml schema.

And it needs to be this way because only in the last phase of creating SIPs one chooses which SIP Format will be used. Until that phase, one has one or more SIPs, which are composed by Descriptive Metadata objects (of a certain metadata format) and one or more data objects. And those same SIPs are passed by to a specific SIP format builder which knows how to process that information to build a SIP of that format.

For now, we will release two versions:
- RODA-in general version. With E-ARK & BagIt SIP formats. With base EAD 2002, Simple Dublin Core & Key value metadata formats. Package description form disabled for all SIP formats.
- RODA-in hungarian version. With E-ARK, BagIt & Hungarian 4 SIP formats. With Hungarian EAD 2002, Simple Dublin Core, Key value & Documentation metadata formats. Package description form activated for E-ARK & Hungarian SIP 4.

**Comment by hsilva-keep** [comment]
Done.
