### ISSUE TITLE
point to correct bagit specification

### ISSUE THREAD

**Issue by johnscancella** [keeps/roda-in#315]
You are currently using old links to the bagit specification in your README:
https://github.com/keeps/roda-in/blame/master/README.md#L22
https://github.com/keeps/roda-in/blame/master/README.md#L168

You should instead use https://tools.ietf.org/html/draft-kunze-bagit which will point to the most current version.

**Comment by hsilva-keep** [comment]
@johnscancella the first link (L22) actually is correct because we are using BagIt version 0.97 (https://github.com/keeps/commons-ip/blob/1_x/src/main/java/org/roda_project/commons_ip/model/impl/bagit/BagitSIP.java#L149), which is the BagIt version mentioned in the link we have at the moment. 
The second one (L168) will be fixed in order to match the first one.
